# =====================================================================
# 专属于 MCUboot 引导程序的硬件加速配置文件
# =====================================================================

# 明确启用 MCUboot 的 Flash 驱动管理
CONFIG_FLASH=y
# 关闭自动检测（省下 900 字节 IRAM，且解锁 DTR 限制）
CONFIG_ESPTOOLPY_FLASH_MODE_AUTO_DETECT=n
# 强制开启八线Octal Flash支持
CONFIG_ESPTOOLPY_OCT_FLASH=y
# 强制开启最高速的 DTR（双倍速率）采样模式
CONFIG_ESPTOOLPY_FLASH_SAMPLE_MODE_DTR=y
# 强制指定 Flash 大小为 32MB
CONFIG_ESPTOOLPY_FLASHSIZE_32MB=y
