# ==============================================================================
# SYSBUILD 全局多镜像组织配置文件
# ==============================================================================

# 告诉系统我们要启用 MCUboot 引导
SB_CONFIG_BOOTLOADER_MCUBOOT=y
